plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  eslint-config-next@*:
    peerDependencies:
      next: "*"
  "@storyblok/js@*":
    peerDependencies:
      axios: "*"
  "@storyblok/react@*":
    peerDependencies:
      axios: "*"
